development:
  adapter: postgresql
  encoding: unicode
  database: indigo_development
  pool: 5
  password:
  template: template0
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: indigo_test
  pool: 5
  password:
  template: template0
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: indigo_production
  pool: 5
  password:
  template: template0
  host: localhost
